apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    type: restapi
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 3
  template:
    metadata:
      name: flaskapp-tmpl
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp-cont
          image: gangadhartiger/azure_flask_app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
